apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: checkout-shoppinglist-api
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: checkout-shoppinglist-api
    spec:
      containers:
      - name: checkout-shoppinglist-api
        image: fkhoda/checkout-shoppinglist-api:latest
        env:
          - name: ES_URL
            value: http://elasticsearch:9200
          - name: ES_INDEX
            value: checkout
          - name: ES_RECREATEINDEXONSTARTUP
            value: "false"
        ports:
        - containerPort: 5000
